config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "people#index"

  # root "articles#index"
  # root "view_demo#index"
  get "art", to:"view_demo#index"
  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"
  resources :articles do
    resources :comments
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  # has_many :comments, dependent: :destroy
  # validates_associated :comments

  # validates :title, presence: true
  # validates :body, presence: true, length: { minimum: 10 }
  has_many :sources, as: :sourceable
end

app/models/bicycle.rb
class Bicycle < Vehicle
end

app/models/car.rb
class Car < Vehicle
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
end

app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :students
end

app/models/emp_account.rb
class EmpAccount < ApplicationRecord
  belongs_to :employee
  has_one :emp_account_history
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_one :emp_account, dependent: :destroy
  # has_one :emp_account_history, :through => :emp_account
  has_one :emp_account_history, through: :emp_account
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :sources, as: :sourceable
end

app/models/news.rb
class News < ApplicationRecord
  has_many :sources, as: :sourceable
end

app/models/person.rb
class Person < ApplicationRecord
  # self.primary_key = "person_id"



  # validates :name, length: { minimum: 2 }, presence: true
  # # validates :terms_of_service, acceptance: true
  #   validates :terms_of_service, acceptance: { message: 'must be abided' }end
  #     validates :terms_of_service, acceptance: { accept: 'yes' }
    # validates :email, confirmation: true
      validates :email_confirmation, presence: {strict: true}

      # validates :name, length: { maximum: 5,
    # too_long: "%{count} characters is the maximum allowed" }

      validates :points, numericality: true
      # validates :games_played, numericality: { only_integer: true }
      has_many :phone_numbers


      validate :points_check
      
      def points_check
        if points>100
          errors.add(:points, "can't be greater than 100")
        end
      end
    
end

# class GoodnessValidator < ActiveModel::Validator
#   def validate(record)
#     if record.name == "Evil"
#       record.errors.add :base, "This person is evil"
#     end
#   end
# end

# class Person < ApplicationRecord
#   validates_with GoodnessValidator
# end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :student_projects
  has_many :students, through: :student_projects
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :sourceable, polymorphic: true
end
  

app/models/student.rb
class Student < ApplicationRecord
  has_one :enrollment
  has_and_belongs_to_many :courses
  has_many :student_projects
  has_many :projects, through: :student_projects, dependent: :destroy
end

app/models/student_project.rb
class StudentProject < ApplicationRecord
  belongs_to :student
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  validates :lastname, length:{minimum:5}
  # before_validation :normalize_lastname, on: [ :create, :update ]
  before_save :save_value_before
  after_save :save_value_after
  before_validation :ensure_login_has_a_value
  after_validation :get_login_value
  before_create :before_creation 
  after_create :after_creation
  after_initialize :after_initialization
  before_update :before_updation 
  after_update :after_updation
  after_touch :after_touching
  after_rollback
  
  # has_many :accounts
 
  def get_login_value
    puts "after validation"
    # puts ".......#{self.login}"
  end

  def ensure_login_has_a_value
    puts "before validation"
    if login.nil?
      self.login = email unless email.blank?
    end
  end 

  def save_value_before
    puts "Inside before save.................."
  end

  def save_value_after
    puts "Inside after save.................."
  end

  def before_creation 
    puts "Before creation"
  end

  def after_creation 
    puts "After creation"
  end

  def before_updation
    puts "before update"
  end

  def after_updation
    puts "after update"
  end
  
    def normalize_lastname
      self.lastname = lastname.downcase.titleize
    end

     def after_initialization
      puts "after initialize"
    end
  
    after_find do |user|
      puts "after find" 
    end

    def after_touching
        puts "You have touched an object"
    end

   

     before_destroy do |user|
      puts "before_destroy"
    end

     after_destroy do |user|
      puts "after_destroy"
    end

     after_commit  do |user|
      puts "after_commit"
    end

     after_rollback do |user|
      puts "after_rollback"
    end

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "ishika", password: "ishika123", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new 
  end

  def create
    # @article = Article.new(title: "...", body: "...")
    @article = Article.new(article_params)    
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<%
=begin%>
 <h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= article.title %>
    </li>
  <% end %>
</ul> 
<%
=end%>

<%
=begin%>
 <h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <a href="/articles/<%= article.id %>">
        <%= article.title %>
      </a>
    </li>
  <% end %>
</ul> 
<%
=end%>

<%
=begin%>
 <h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <a href="<%= article_path(article) %>">
        <%= article.title %>
      </a>
    </li>
  <% end %>
</ul> 
<%
=end%>

<%
=begin%>
 <h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul> 
<%
=end%>

<%
=begin%>
 <h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %> 
<%
=end%>

<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<%
=begin%>
 <h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %> 
<%
=end%>


<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>